### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by Sidriband** [pushcodeveryday/Biometric-Fingerprint-Integration#4]
Thanks a lot for the script, I'm a beginner in this area and would like to study your biometrics system, could you make the login file or the complete project available?

**Comment by princesinha19** [comment]
No sorry @Sidriband. The whole project is confidential. Bdw, You can get a simple PHP authentication module from the internet and then, you can use this SDK to do fingerprint biometric authentication using Mantra MFS 1000 device.
